---
# roles/mgmt-controller/install_tools/tasks/main.yml
# Created: 2019-10-15
# cdex-deploy
# Purpose:
#
#    
#    

- name: install pip3
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name: python3-pip
    state: present

#- name: check for boto/boto3 in virtualenv
#  pip:
#    name: ["boto", "boto3"]
#    state: present
#    virtualenv: "{{ base_app_directory }}/{{ role_type }}/{{ virtual_env_dir }}"

- name: check for boto/boto3 in baseenv
  become_user: "{{ remote_admin_account }}"
  become: yes
  pip:
    name: ["boto", "boto3"]
    state: present
