# app_server.yml
---
# playbook that runs our app server tasks for any hosts in the `vpc` group, providing AWS credentials in the environment

- hosts: vpc
  vars_files:
    - "group_vars/abhealth-env-{{ vpc_env|lower }}.yml"
  vars:
    role_state: present
    platform_app:
      - "vmi"
      - "smh"
      - "smhapp"


  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_REGION: "{{ aws_region }}"
  tasks:

    - include_tasks: tasks/app/vmi/get_instance_info.yml

      
