# app_server.yml
---
# playbook that runs our app server tasks for any hosts in the `vpc` group, providing AWS credentials in the environment

- hosts: "localhost"
  vars_files:
    - "group_vars/abhealth-env-{{ vpc_env|lower }}.yml"
  vars:
    role_state: present
    platform_app:
      - "vmi"
      - "smh"
      - "smh_app"
    base_ami: "ami-07d0cf3af28718ef8"
    ec2_app_instance_type:
      vmi: "t2.micro"
      smh: "t2.medium"
      smh_app: "t2.large"
    ec2_instance_volsize:
      vmi: 20
      smh: 21
      smh_app: 22

    role_type: "vmi"
    # ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20190722.1 (ami-07d0cf3af28718ef8)

    # default vpc to create base instance:
    default_vpc_id: "vpc-86e735fc"
    # default subnet-id for base instance
    default_subnet_id: "subnet-1464e93a"

    # Key pair name:
    key_pair: "abhealth-{{ vpc_env }}-servers"


  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_REGION: "{{ aws_region }}"
  tasks:

    # - include_tasks: tasks/app/vmi/get_instance_info.yml
    - include_tasks: "tasks/app/create_instance.yml"
      vars:
          variable_host: "localhost"

    - include_tasks: "tasks/app/nginx_install.yml"
      vars:
          variable_host: "tag_function_BaseInstance:tag_workflow_JustCreated"


