# vpc.yml
---
# playbook that runs our VPC tasks for any hosts in the `vpc` group, providing AWS credentials in the environment

- hosts: vpc
  vars_files:
    - "group_vars/abhealth-env-{{ vpc_env|lower }}.yml"
  vars:
    role_state: present
    platform_app:
      - "vmi"
      - "smh"
      - "smhapp"


  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_REGION: "{{ aws_region }}"
  tasks:

    - include_tasks: tasks/vpc/setup.vpc.yml
    - include_tasks: tasks/vpc/setup.gateways.yml
    - include_tasks: tasks/vpc/setup.alb.yml
      with_items:
        - { platform_app: "vmi", alb_scheme: "internet-facing", ports: [80, 443], protocols: ["http", "https"] }
        - { platform_app: "smh", alb_scheme: "internet-facing", ports: [80, 443], protocols: ["http", "https"] }
        - { platform_app: "smhapp", alb_scheme: "internet-facing", ports: [80, 443], protocols: ["http", "https"] }
    - include_tasks: tasks/vpc/facts.yml
