---
# roles/deploy_make/tasks/main.yml
# Created: 2019-09-11
# cdex-deploy
# Purpose:
#
#    

- name: "create ami from server {{ variable_host }}"
  ec2_ami:
    instance_id: "{{ ec2_facts_info_id.instances.0.instance_id }}"
    wait: yes
    name:  "{{ vpc_env }}_{{ role_type }}_{{ ansible_date_time.iso8601_basic_short }}"
    tags:
      Name: "{{ vpc_env }}_{{ role_type }}_{{ ansible_date_time.iso8601_basic_short }}"
      env: "{{ vpc_env }}"
      function: "{{ role_type }}"
      role:  "{{ role_type }}"
      birth: "{{ ansible_date_time.iso8601_basic_short }}"
      release: "{{ replacement_time }}"
      mode: "readytoattach"
  register: ami_info
  ignore_errors: true

# find ami
- name: find ami
  debug:
    msg: "Created AMI: {{ ami_info.image_id }}"

- name: "Update Launch Template for {{ vpc_env }}-{{ role_type }} using {{ variable_host }} AMI: {{ ami_info.image_id }}"
  ec2_launch_template:
    name: "{{ vpc_env }}-{{ role_type }}-LT"
    image_id: "{{ ami_info.image_id }}"
    key_name: "{{ ansible_ssh_private_key_name }}"
    instance_type: "{{ec2_app_instance_type[role_type] }}"
    state: present
    region: "{{ aws_region }}"
    tags:
      name: "{{ vpc_env }}-{{ role_type }}-LT"
      env: "{{ vpc_env }}"
      role: "{{ role_type }}"
      function: "LaunchTemplate"
    security_group_ids: "{{ app_security_group_id[vpc_env][role_type] }}"
  register: launch_template_info

#- name: "what did we get?"
#  debug:
#    msg: "{{ launch_template_info }}"

