---
# roles/letsencrypt/tasks/main.yml
# Created: 2019-09-11
# cdex-deploy
# Purpose:
# Install Let's Encrypt with certbot
#    
#    

- name: "update before letsencrypt install"
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: "sudo apt-get -y update"

- name: "prepare for let's encrypt"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name: "software-properties-common"
    state: present

- name: "repository update"
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: "sudo add-apt-repository -y universe && sudo add-apt-repository -y ppa:certbot/certbot"

- name: "re-update for letsencrypt install"
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: "sudo apt-get -y update"

- name: "Certbot install"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name: "{{ item }}"
    state:  present
  with_items:
    - certbot
    - python-certbot-nginx

- name: "configure certbot for nginx"
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: "sudo certbot --nginx"
  # or
  # shell: "sudo certbot certonly --nginx"

