---
# roles/docker_launch/tasks/main.yml
# Created: 2019-09-05
# cdex-deploy
# Purpose:
#  Build and run docker app
#    

- name: "Tear down existing services: {{ role_type }} ( {{ system_repository_name[role_type] }})"
  docker_compose:
    project_src: "/home/{{ remote_user_account }}/cdex.{{ vpc_env }}"
    services: "{{ system_repository_name[role_type] }}"
    state: absent

- name: Download .env file
  template:
    src: "templates/{{ role_type }}_env_file"
    dest: "/home/{{ remote_user_account }}/cdex.{{ vpc_env }}/.env"
    owner: "{{ remote_user_account }}"
    mode: 0664

- name: Create and start services
  docker_compose:
    project_src: "/home/{{ remote_user_account }}/cdex.{{ vpc_env }}"
    services: "{{ system_repository_name[role_type] }}"
  register: output

- debug:
    var: output

- name: Run `docker-compose up` again
  docker_compose:
    project_src: "/home/{{ remote_user_account }}/cdex.{{ vpc_env }}"
    services: "{{ system_repository_name[role_type] }}"
    build: no
  register: output

- debug:
    var: output

- assert:
    that: "not output.changed "

- name: Stop all services
  docker_compose:
    project_src: "/home/{{ remote_user_account }}/cdex.{{ vpc_env }}"
    services: "{{ system_repository_name[role_type] }}"
    build: no
    stopped: yes
  register: output

- debug:
    var: output

- name: Restart services
  docker_compose:
    project_src: "/home/{{ remote_user_account }}/cdex.{{ vpc_env }}"
    services: "{{ system_repository_name[role_type] }}"
    build: no
    restarted: yes
  register: output

- debug:
    var: output
