---
# roles/logrotate/tasks/main.yml
# Created: 2020-02-18
# cdex-deploy
# Purpose:
#  setup log file for sharemyhealth.conf
#  in /etc/rsyslog.d/30-sharemyhealth.conf

- name: "create the rsyslog configuration file for django"
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: templates/30-sharemyhealth.conf
    dest: "/etc/rsyslog.d/30-sharemyhealth.conf"
    mode: "0755"
    owner: "{{ remote_admin_account }}"
    group: "{{ remote_admin_account }}"

- name: "restart rsyslog"
  become_user: "{{ remote_admin_account }}"
  become: yes
  service:
    name: rsyslog
    state: restarted
    enabled: yes

- name: "setup logrotate for django sharemyhealth.log"
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: templates/sharemyhealth
    dest: "/etc/logrotate.d/sharemyhealth"
    mode: "0755"
    owner: "{{ remote_admin_account }}"
    group: "{{ remote_admin_account }}"


- name: "setup logrotate for gunicorn_supervisor.log"
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: templates/gunicorn_supervisor
    dest: "/etc/logrotate.d/gunicorn_supervisor"
    mode: "0755"
    owner: "{{ remote_admin_account }}"
    group: "{{ remote_admin_account }}"

