---
# roles/deploy/ready/tasks/main.yml
# Created: 2019-09-11
# cdex-deploy
# Purpose: update tags on server to identify deployment readiness
#
#    
#


- name: get ec2 facts
  become_user: "{{ remote_admin_account }}"
  become: yes
  ec2_instance_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
  register: ec2_facts_info

- name: "Get resource_id of ec2_instance"
  debug:
    msg: "{{ ec2_facts_info }}"

- name: "get ec2 facts for {{ vpc_env }}_{{ role_type }}_server - source"
  become_user: "{{ remote_admin_account }}"
  become: yes
  ec2_instance_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:workflow": "source"
      "tag:Name": "{{ vpc_env }}_{{ role_type }}_server"
  register: ec2_facts_info_id

- name: "Get resource_id of ec2_instance"
  debug:
    msg: "{{ ec2_facts_info_id.instances.0.instance_id }}"


 disable section until operational
- name: "update ec2 tags on built ec2 instance"
  ec2_tag:
    region: "{{ aws_region }}"
    resource: "{{ ec2_facts_info_id.instances.0.instance_id }}"
    state: absent
    tags:
      workflow: "source"

- name: "replace ec2_tag"
  ec2_tag:
    region: "{{ aws_region }}"
    resource: "{{ ec2_facts_info_id.instances.0.instance_id }}"
    state: present
    tags:
      workflow: "release"
      release: "{{ replacement_time }}"


