# tasks/vpc/setup.alb.yml
---

# The following should come in as item
#  alb_list:
#    - { platform_app: "vmi", ports: [80, 443], protocols: ["http", "https"] }
#    - { platform_app: "smh", ports: [80, 443], protocols: ["http", "https"] }
#    - { platform_app: "smhapp", ports: [80, 443], protocols: ["http", "https"] }

# Create an ELB with application stickiness enabled
- name: "Create {{ vpc_env|lower }}-{{ item.platform_app }}-ALB"
  module: elb_application_lb
    name: "{{ vpc_env|lower }}-{{ item }}-ALB"
    state: "{{ role_state }}"
    scheme: "internet-facing"
    region: "{{ aws_region }}"
    zones:
      - "{{ aws_region }}a"
      - "{{ aws_region }}b"
      - "{{ aws_region }}c"
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
        proxy_protocol: True
      - protoccol: https
        load_balancer_port: 443
        instance_protocol: http
        instance_port: 80
    security_group_names:
      - "{{ vpc_env }}-DMZ"
    stickiness:
      type: application
      enabled: yes
      cookie: SESSIONID
  register: "alb_instance.{{ item }}"

