# tasks/vpc/setup.alb.yml
---

# The following should come in as item
#  alb_list:
#    - { platform_app: "vmi", ports: [80, 443], protocols: ["http", "https"] }
#    - { platform_app: "smh", ports: [80, 443], protocols: ["http", "https"] }
#    - { platform_app: "smhapp", ports: [80, 443], protocols: ["http", "https"] }

# Create an ELB with application stickiness enabled
- elb_application_lb:
    name: "{{ vpc_env }}-vmi-ALB"
    state: "{{ role_state }}"
    scheme: "internet-facing"
    region: "{{ aws_region }}"
    subnets:
      - "{{ vpc_subnets['dmz-a'] }}"
      - "{{ vpc_subnets['dmz-b'] }}"
      - "{{ vpc_subnets['dmz-c'] }}"
    listeners:
      # Certificates, DefaultActions, Port, Protocol, Rules, SslPolicy
      - Protocol: http
        Port: 80
      - Protoccol: https
        Port: 443
    security_groups:
      - "{{ vpc_env }}-DMZ"
  register: "alb_instance_vmi"

# Create an ELB with application stickiness enabled
- elb_application_lb:
    name: "{{ vpc_env }}-smh-ALB"
    state: "{{ role_state }}"
    scheme: "internet-facing"
    region: "{{ aws_region }}"
    zones:
      - "{{ aws_region }}a"
      - "{{ aws_region }}b"
      - "{{ aws_region }}c"
    listeners:
      # Certificates, DefaultActions, Port, Protocol, Rules, SslPolicy
      - Protocol: http
        Port: 80
      - Protoccol: https
        Port: 443
    security_groups:
      - "{{ vpc_env }}-DMZ"
  register: "alb_instance_smh"

# Create an ELB with application stickiness enabled
- elb_application_lb:
    name: "{{ vpc_env }}-smh-ALB"
    state: "{{ role_state }}"
    scheme: "internet-facing"
    region: "{{ aws_region }}"
    zones:
      - "{{ aws_region }}a"
      - "{{ aws_region }}b"
      - "{{ aws_region }}c"
    listeners:
      # Certificates, DefaultActions, Port, Protocol, Rules, SslPolicy
      - Protocol: HTTP
        Port: 80
      - Protoccol: HTTPS
        Port: 443
        DefaultActions:
          - Type: forward
            TargetGroupName: test-target-group
        SslPolicy: ELBSecurityPolicy-2015-05

    security_groups:
      - "{{ vpc_env }}-DMZ"
  register: "alb_instance_smhapp"
