# tasks/vpc/setup.alb.yml
---

# The following should come in as item
#  alb_list:
#    - { platform_app: "vmi", ports: [80, 443], protocols: ["http", "https"] }
#    - { platform_app: "smh", ports: [80, 443], protocols: ["http", "https"] }
#    - { platform_app: "smhapp", ports: [80, 443], protocols: ["http", "https"] }

- debug:
    msg: "VPC Security Groups: {{ vpc_security_groups }}"

- ec2_vpc_subnet_facts:
    filters:
      "tag:Name": "{{ item }}"
  loop:
    - "{{ vpc_env|upper}}-dmz-a"
    - "{{ vpc_env|upper}}-dmz-b"
    - "{{ vpc_env|upper}}-dmz-c"
  register: subnet_facts

- debug:
    msg: "subnet_facts: \n {{ subnet_facts.results }}"

- set_fact:
    subnet_ids: []

- debug:
    msg: "we got this: {{ item.subnets[0].subnet_id }}"
  with_items:
    - "{{ subnet_facts.results }}"


- set_fact:
    subnet_ids: "{{ subnet_ids + [ item.subnets[0].subnet_id ] }}"
  with_items:
    - "{{ subnet_facts.results }}"
#    subnet_ids: "{% for i in range(0,(subnet_facts.results)|length ) %}{{subnet_facts.results[i].subnets[0].subnet_id }},{% endfor %}"

- debug:
    msg: "vpc subnets: {{ subnet_ids }}"

- elb_target_group_facts:
    names:
      - "{{ vpc_env }}-vmi-APP"
  register: alb_targetgroupfacts_vmi

- debug:
    msg: "Target Group Facts:\n{{ alb_targetgroupfacts_vmi.target_groups[0].target_group_arn }}"

# Create an ELB with application stickiness enabled
- elb_application_lb:
    name: "{{ vpc_env }}-vmi-ALB"
    state: "{{ role_state }}"
    scheme: "internet-facing"
    region: "{{ aws_region }}"
    security_groups:
      - "{{ vpc_env }}-DMZ"
    subnets: "{{ subnet_ids }}"
    listeners:
      # Certificates, DefaultActions, Port, Protocol, Rules, SslPolicy
      - Protocol: HTTPS
        Port: 443
        Certificates:
        DefaultActions:
          - Type: forward
            TargetGroupName: "{{ vpc_env }}-vmi-APP"
            # "{{ alb_targetgroupfacts_vmi.target_groups[0].target_group_arn }}"
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: redirect
            TargetGroupName: "staging-vmi-APP"
        SslPolicy: "ELBSecurityPolicy-2016-08"
  register: "alb_instance_vmi"

## Create an ELB with application stickiness enabled
#- elb_application_lb:
#    name: "{{ vpc_env }}-smh-ALB"
#    state: "{{ role_state }}"
#    scheme: "internet-facing"
#    region: "{{ aws_region }}"
#    security_groups:
#      - "{{ vpc_env }}-DMZ"
#    subnets:
#      - "{{ vpc_subnets['dmz-a'] }}"
#      - "{{ vpc_subnets['dmz-b'] }}"
#      - "{{ vpc_subnets['dmz-c'] }}"
#    listeners:
#      # Certificates, DefaultActions, Port, Protocol, Rules, SslPolicy
#      - Protocol: http
#        Port: 80
#      - Protocol: https
#        Port: 443
#          DefaultActions:
#          - Type: forward
#            TargetGroupName: "{{ vpc_env }}-smh-APP"
#        SslPolicy: ELBSecurityPolicy-2015-05
#  register: "alb_instance_smh"
#
## Create an ELB with application stickiness enabled
#- elb_application_lb:
#    name: "{{ vpc_env }}-smhapp-ALB"
#    state: "{{ role_state }}"
#    scheme: "internet-facing"
#    region: "{{ aws_region }}"
#    security_groups:
#      - "{{ vpc_env }}-DMZ"
#    subnets:
#      - "{{ vpc_subnets['dmz-a'] }}"
#      - "{{ vpc_subnets['dmz-b'] }}"
#      - "{{ vpc_subnets['dmz-c'] }}"
#    listeners:
#      # Certificates, DefaultActions, Port, Protocol, Rules, SslPolicy
#      - Protocol: HTTP
#        Port: 80
#      - Protocol: HTTPS
#        Port: 443
#        DefaultActions:
#          - Type: forward
#            TargetGroupName: "{{ vpc_env }}-smhapp-APP"
#        SslPolicy: ELBSecurityPolicy-2015-05
#  register: "alb_instance_smhapp"
