# tasks/vpc/setup.alb.yml
---

# The following should come in as item
#  alb_list:
#    - { platform_app: "vmi", ports: [80, 443], protocols: ["http", "https"] }
#    - { platform_app: "smh", ports: [80, 443], protocols: ["http", "https"] }
#    - { platform_app: "smhapp", ports: [80, 443], protocols: ["http", "https"] }

- debug:
    msg: "VPC Security Groups: {{ vpc_security_groups }}"

- elb_target_group_facts:
    names:
      - "{{ vpc_env }}-vmi-APP"
  register: alb_targetgroupfacts_vmi

- debug:
    msg: "Target Group Facts:\n{{ alb_targetgroupfacts_vmi.target_groups[0].target_group_arn }}"

# Create an ELB with application stickiness enabled
- elb_application_lb:
    name: "{{ vpc_env }}-vmi-ALB"
    state: "{{ role_state }}"
    scheme: "internet-facing"
    region: "{{ aws_region }}"
    security_groups:
      - "{{ vpc_env }}-DMZ"
    subnets:
      - "{{ vpc_subnets['dmz-a'].cidr }}"
      - "{{ vpc_subnets['dmz-b'].cidr }}"
      - "{{ vpc_subnets['dmz-c'].cidr }}"
    listeners:
      # Certificates, DefaultActions, Port, Protocol, Rules, SslPolicy
      - Protocol: http
        Port: 80
        DefaultActions:
          - Type: forward
            TargetGroupName: "{{ alb_targetgroupfacts_vmi.target_groups[0].target_group_arn }}"
      - Protocol: https
        Port: 443
        DefaultActions:
          - Type: forward
            TargetGroupName: "staging-vmi-APP"
        SslPolicy: ELBSecurityPolicy-2015-05
  register: "alb_instance_vmi"

## Create an ELB with application stickiness enabled
#- elb_application_lb:
#    name: "{{ vpc_env }}-smh-ALB"
#    state: "{{ role_state }}"
#    scheme: "internet-facing"
#    region: "{{ aws_region }}"
#    security_groups:
#      - "{{ vpc_env }}-DMZ"
#    subnets:
#      - "{{ vpc_subnets['dmz-a'] }}"
#      - "{{ vpc_subnets['dmz-b'] }}"
#      - "{{ vpc_subnets['dmz-c'] }}"
#    listeners:
#      # Certificates, DefaultActions, Port, Protocol, Rules, SslPolicy
#      - Protocol: http
#        Port: 80
#      - Protocol: https
#        Port: 443
#          DefaultActions:
#          - Type: forward
#            TargetGroupName: "{{ vpc_env }}-smh-APP"
#        SslPolicy: ELBSecurityPolicy-2015-05
#  register: "alb_instance_smh"
#
## Create an ELB with application stickiness enabled
#- elb_application_lb:
#    name: "{{ vpc_env }}-smhapp-ALB"
#    state: "{{ role_state }}"
#    scheme: "internet-facing"
#    region: "{{ aws_region }}"
#    security_groups:
#      - "{{ vpc_env }}-DMZ"
#    subnets:
#      - "{{ vpc_subnets['dmz-a'] }}"
#      - "{{ vpc_subnets['dmz-b'] }}"
#      - "{{ vpc_subnets['dmz-c'] }}"
#    listeners:
#      # Certificates, DefaultActions, Port, Protocol, Rules, SslPolicy
#      - Protocol: HTTP
#        Port: 80
#      - Protocol: HTTPS
#        Port: 443
#        DefaultActions:
#          - Type: forward
#            TargetGroupName: "{{ vpc_env }}-smhapp-APP"
#        SslPolicy: ELBSecurityPolicy-2015-05
#  register: "alb_instance_smhapp"
