# tasks/vpc/setup.targetgroup.yml
# create VPC target Groups.

- debug:
    msg: "setting up target group {{  vpc_env}}-{{ item }}-APP"
# Create a target group with a default health check
- elb_target_group:
    name: "{{  vpc_env}}-{{ item }}-APP"
    protocol: http
    port: 80
    vpc_id: "{{ vpc_id }}"
    state: present
