# tasks/vpc/setup.alb.yml
---


# Create an ELB with application stickiness enabled
- local_action:
    module: ec2_elb_lb
    name: "{{ vpc_env|lower }}-ALB"
    state: present
    scheme: internet-facing
    region: "{{ aws_region }}"
    zones:
      - "{{ aws_region }}a"
      - "{{ aws_region }}b"
      - "{{ aws_region }}c"
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
        proxy_protocol: True
      - protoccol: https
        load_balancer_port: 443
        instance_protocol: http
        instance_port: 80
    security_group_names:
      - "{{ vpc_env }}-DMZ"

    stickiness:
      type: application
      enabled: yes
      cookie: SESSIONID
