---
# roles/cda2fhir_get_ip/aws_get_ip/tasks/main.yml
# Created: 2019-11-08
# cdex-deploy
# Purpose:  Get private Ip via AWS Tags

- name: "get cda2fhir private ip in {{ vpc_env }}"
  ec2_instance_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    filters:
      "tag:env": "{{ vpc_env }}"
      "tag:function": "cda2fhir"
      "tag:role": "cda"
      "tag:workflow": "service"
  register: cda2fhir_info
  delegate_to: localhost

#- debug:
#    msg: "CDA2FHIR Private IP Address:{{ cda2fhir_info.instances.0.private_ip_address }}"
#    # msg:  "EC2 Instance:\n{{ cda2fhir_info | to_nice_yaml }}"
#    # msg:  "EC2 Instance:\n{{ cda2fhir_info | to_nice_json }}"

- name: "Save cda2fhir private Ip Address:{{ cda2fhir_info.instances.0.private_ip_address }}"
  set_fact:
    cda2fhir_private_ip: "{{ cda2fhir_info.instances.0.private_ip_address }}"

- name: "check CDA2FHIR Service is up and operating correctly "
  uri:
    url: "http://{{ cda2fhir_private_ip }}:{{ cda2fhir_service_port }}/api/convert"
    status_code: ["200", "301"]
    return_content: yes
  register: cda2fhir_check

- name: "result of http://{{ cda2fhir_private_ip }}:{{ cda2fhir_service_port }}/api/convert call"
  debug:
    msg:
      - "RETURNED: {{ cda2fhir_check.status }}"
      - "REDIRECTED: {{ cda2fhir_check.redirected }}"
      - "BODY:"
      - "{{ cda2fhir_check.content }}"

