---
# playbook/server/docker_base_configure.yml

#  install the git repos needed to build docker containers

- name: configure server
  hosts: "{{ variable_host| default('tag_function_BaseInstance:tag_workflow_JustCreated:tag_Name_BaseInstance_Docker') }}"
  remote_user: "{{ remote_user_account }}"
  vars:
    ansible_ssh_pipelining: no
    env: "{{ vpc_env }}"
    # Options - lower case: staging | prod
    azone: "az1"
    # Options: az1 | az2 | az3
    sub_zone: "app"
    role_type: "vmi"
    # Options: vmi | smh | smhapp

    sg_zone: "{{ vpc_env }}-{{ role_type }}-APP"
    env_az: "{{ vpc_env }}-{{ azone }}"
    #    env_cf_data_version: "20"
    #    env_cf_app_version: "01"
    build_subnet_id: null
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/environment/{{ vpc_env }}/vault.yml"
    - "./../../vars/environment/{{ vpc_env }}/env.yml"

  roles:
    - "../../roles/docker_python"
    - "../../roles/docker_launch"


