---
# 2019-08-29.21:43 - mark
# cdex-deploy
# roles/base_patch/tasks/main.yml

- name: "install aptitude"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name: aptitude
    state: latest

- name: "update packages"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name: "*"
    state: latest
