---
# 2019-08-29.21:43 - mark
# cdex-deploy
# roles/base_patch/tasks/main.yml

- name: "install aptitude"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name: aptitude
    state: latest

- name: "update packages"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name: "*"
    state: latest

- name: "APT upgrade/update"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: "Add packages"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
#    - jpeg-dev
#    - zlib-dev
    - libffi-dev
    - libssl-dev
    - zlib1g-dev
#    - openssh
    - gcc
#    - build-base
#    - linux-headers
#    - pcre-dev
#    - postgresql-dev
#    - musl-dev
    - libxml2-dev
    - libxslt-dev
    - nginx
    - curl
#    - supervisor
    - git


