---
# roles/deploy_make/tasks/main.yml
# Created: 2019-09-11
# cdex-deploy
# Purpose:
#
#    

- name: "create ami from server"
  ec2_ami:
    instance_id: "{{ ec2_facts_info_id.instances.0.instance_id }}"
    wait: yes
    name:  "{{ role_type }}_{{ ansible_date_time.iso8601_basic_short }}"
    tags:
      Name: "{{ role_type }}_{{ ansible_date_time.iso8601_basic_short }}"
      env: "{{ vpc_env }}"
      function: "{{ role_type }}"
      role:  "{{ role_type }}"




