---
# roles/deploy_make/tasks/main.yml
# Created: 2019-09-11
# cdex-deploy
# Purpose:
#
#    

- name: "create ami from server {{ variable_host }}"
  ec2_ami:
    instance_id: "{{ ec2_facts_info_id.instances.0.instance_id }}"
    wait: yes
    name:  "{{ role_type }}_{{ ansible_date_time.iso8601_basic_short }}"
    tags:
      Name: "{{ role_type }}_{{ ansible_date_time.iso8601_basic_short }}"
      env: "{{ vpc_env }}"
      function: "{{ role_type }}"
      role:  "{{ role_type }}"
      birth: "{{ ansible_date_time.iso8601_basic_short }}"
      mode: "readytoattach"
  register: ami_info
  ignore_errors: true

# find ami
- name: find ami
  debug:
    msg: "Created AMI: {{ ami_info.image_id }}"

# create launch configuration
- name: "build ec2 instance {{ ami_info.tags.Name }}"
  ec2:
    region: "{{ aws_region}}"
    image: "{{ ami_info.image_id }}"
    instance_type: "{{ec2_app_instance_type[role_type] }}"
    wait: yes
    vpc_subnet_id: "{{ vpc_app_subnet_id }}"
    count: 1
    key_name: "{{  }}"
    assign_public_ip: no
    state: present

# get instance id

# add instance to scalable group

# add group to target group

# add target group to ALB





