---
# 2019-08-27.17:41 - mark
# cdex-deploy
# playbook/server/server_base_configure.yml
#
# Configure the server with base components

- name: configure server
  hosts: "{{ variable_host| default('tag_function_BaseInstance:tag_workflow_JustCreated') }}"
  remote_user: "{{ remote_user_account }}"
  vars:
    ansible_ssh_pipelining: no
    env: "{{ vpc_env }}"
    # Options - lower case: staging | prod
    azone: "az1"
    # Options: az1 | az2 | az3
    sub_zone: "app"
    role_type: "{{ role_type| default('vmi') }}"
    # Options: vmi | smh | smh_app

    sg_zone: "{{ vpc_env }}-{{ role_type }}-APP"
    env_az: "{{ vpc_env }}-{{ azone }}"
    #    env_cf_data_version: "20"
    #    env_cf_app_version: "01"
    build_subnet_id: null

  vars_files:
    - "./../../vault/environment/{{ vpc_env }}/{{ role_type }}/vault.yml"
    - "./../../vars/environment/{{ vpc_env }}/{{ role_type }}/env.yml"
    - "./../../vault/environment/{{ vpc_env }}/vault.yml"
    - "./../../vars/environment/{{ vpc_env }}/env.yml"
    - "./../../vars/common.yml"

  roles:
    - role: "../../roles/base_app"
    # install aws config
    - role: "../../roles/aws_config_install"
    - role: "../../roles/python3.7"
      when: "role_type == 'smh_app' "
    - role: "../../roles/app_user"
    - role: "../../roles/app_install"
    - role: "../../roles/postgres_setup"
    - role: "../../roles/configure_app"
    - role: "../../roles/nginx"
    - role: "../../roles/check_web_is_up"

#    - "../../roles/base_app"

#    - "../../roles/aws_config_install"
#    - "../../roles/python3.7"
#    - "../../roles/app_user"
#    - "../../roles/app_install"
#    - "../../roles/postgres_setup"
#    - "../../roles/configure_app"
#    - "../../roles/nginx"
#    - "../../roles/check_web_is_up"
#    - "../../roles/deploy_ready"



