---
# 2019-08-27.17:41 - mark
# cdex-deploy
# playbook/server/server_base_configure.yml
#
# Configure the server with base components

- name: configure server
  hosts: "{{ variable_host| default('tag_function_BaseInstance:tag_workflow_JustCreated') }}"
  remote_user: "{{ remote_user_account }}"
  vars:
    ansible_ssh_pipelining: no
    env: "{{ vpc_env }}"
    # Options - lower case: staging | prod
    azone: "az1"
    # Options: az1 | az2 | az3
    sub_zone: "app"
    role_type: "vmi"
    # Options: vmi | smh | smh_app

    sg_zone: "{{ vpc_env }}-{{ role_type }}-APP"
    env_az: "{{ vpc_env }}-{{ azone }}"
    #    env_cf_data_version: "20"
    #    env_cf_app_version: "01"
    build_subnet_id: null
  vars_files:
    - "./../../vault/environment/{{ vpc_env }}/{{ role_type }}/vault.yml"
    - "./../../vars/environment/{{ vpc_env }}/{{ role_type }}/env.yml"
    - "./../../vault/environment/{{ vpc_env }}/vault.yml"
    - "./../../vars/environment/{{ vpc_env }}/env.yml"
    - "./../../vars/common.yml"


#  pre_tasks:
#    - name: install python
#      become: yes
#      become_user: "{{ remote_admin_account }}"
#      raw: bash -c "sudo apt-get -y install python3.7 python3-pip python3.7-dev python3.7-venv python3-apt"
#
#      register: output
#      changed_when: output.stdout != ""

  roles:
    - "../../roles/base_patch"
    - "../../roles/python"
    - "../../roles/app_user"
    - "../../roles/app_install"
    - "../../roles/nginx"


