---
# 2019-08-27.17:41 - mark
# cdex-deploy
# playbook/server/server_base_configure.yml
#
# Configure the server with base components

- name: configure server
  hosts: "{{ variable_host| default('tag_function_BaseInstance:tag_workflow_JustCreated') }}"
# gather_facts: "{{ gather_facts| default('yes') }}"
  remote_user: "{{ remote_user_account }}"
  vars:
    ansible_ssh_pipelining: no
    env: "{{ vpc_env }}"
    # Options - lower case: staging | prod
    azone: "az1"
    # Options: az1 | az2 | az3
    sub_zone: "app"
    role_type: "{{ role_type| default('vmi') }}"
    # Options: vmi | smh | smh_app
    make_migration: "no"
    #options: no | yes

    sg_zone: "{{ vpc_env }}-{{ role_type }}-APP"
    env_az: "{{ vpc_env }}-{{ azone }}"
    #    env_cf_data_version: "20"
    #    env_cf_app_version: "01"
    build_subnet_id: null
    configure_time: "{{ ansible_date_time.iso8601_basic_short }}"

  vars_files:
    - "./../../vault/environment/{{ vpc_env }}/{{ role_type }}/vault.yml"
    - "./../../vars/environment/{{ vpc_env }}/{{ role_type }}/env.yml"
    - "./../../vault/environment/{{ vpc_env }}/vault.yml"
    - "./../../vars/environment/{{ vpc_env }}/env.yml"
    - "./../../vars/common.yml"

  roles:
    # install boto3 to support CDA2FHIR Service query
    - role: "../../roles/pip_boto"
    # Get the CDA2FHIR service
    - role: "../../roles/cda2fhir_get_ip/aws_get_ip"
    - role: "../../roles/app/base"
    # install aws config
    - role: "../../roles/aws/config_install"
    # install cloudwatch agent
    - role: "../../roles/aws/cloudwatch_install"

    - role: "../../roles/app/user"

    - role: "../../roles/python/python3.7"
      when: role_type == 'smh_app'

    - role: "../../roles/app/install"
    - role: "../../roles/postgres_setup"
    - role: "../../roles/app/configure"
    - role: "../../roles/logrotate"
    - role: "../../roles/nginx"
    - role: "../../roles/check_web_is_up"

    - role: "../../roles/notify/slack/tasks/generic.yml"
      notify_msg: "{{ vpc_env|upper }}: {{ configure_time }} - CDA2FHIR Service ({{ cda2fhir_private_ip }}:{{ cda2fhir_service_port }}) reported: {{ cda2fhir_check.content }}"
      notify_slack_channel: "#afbh-updates"
      notify_slack_user: "afbh-mgmt-controller"
      when: role_type == "smh"

    - role: "../../roles/notify/slack/tasks/generic.yml"
      notify_msg: "{{ role_type }} updated in {{ vpc_env }} at {{ configure_time }} from https://github.com/TransparentHealth/{{ system_repository_name[role_type] }} Branch: {{ git_branch[role_type] }}"
      notify_slack_channel: "#afbh-updates"
      notify_slack_user: "afbh-mgmt-controller"

    - role: "../../roles/notify/team/tasks/generic.yml"
      notify_msg: "{{ vpc_env|upper }}: {{ configure_time }} - CDA2FHIR Service ({{ cda2fhir_private_ip }}:{{ cda2fhir_service_port }}) reported: {{ cda2fhir_check.content }}"
      notify_teams_webhook: "{{ teams_webhook }}"
      when: role_type == "smh"

    - role: "../../roles/notify/team/tasks/generic.yml"
      notify_msg: "{{ role_type }} updated in {{ vpc_env }} at {{ configure_time }} from https://github.com/TransparentHealth/{{ system_repository_name[role_type] }} Branch: {{ git_branch[role_type] }}"
      notify_team_hook:  "{{ teams_webhook }}"

