---
# 2019-08-27.17:41 - mark
# cdex-deploy
# playbook/server/server_app_parameters.yml
#
# Check out AWS SSM Parameter Store

- name: configure server
  hosts: "{{ variable_host| default('tag_function_BaseInstance:tag_workflow_JustCreated') }}"
  remote_user: "{{ remote_user_account }}"
  vars:
    ansible_ssh_pipelining: no
    env: "{{ vpc_env }}"
    # Options - lower case: staging | prod
    azone: "az1"
    # Options: az1 | az2 | az3
    sub_zone: "app"
    role_type: "{{ role_type| default('vmi') }}"
    # Options: vmi | smh | smhapp

    sg_zone: "{{ vpc_env }}-{{ role_type }}-APP"
    env_az: "{{ vpc_env }}-{{ azone }}"
    #    env_cf_data_version: "20"
    #    env_cf_app_version: "01"
    build_subnet_id: null
  vars_files:
    - "./../../vars/common.yml"
    - "./../../vault/environment/{{ vpc_env }}/vault.yml"
    - "./../../vars/environment/{{ vpc_env }}/env.yml"

  tasks:
    - name: "Check pout parameter store"
      debug:
        msg: "{{ lookup('aws_ssm', '/dev/vmi', region='us-east-1', bypath=true, recursive=true ) }}"
