---
# playbook/server/server_app_deploy.yml
# Created: 2019-09-11
# cdex-deploy
# Purpose: deploy server to ALB
#

- name: deploy server
  hosts: localhost
  connection: local
  # hosts: "{{ variable_host| default('tag_function_BaseInstance:tag_workflow_JustCreated') }}"
  remote_user: "{{ remote_user_account }}"
  vars:
    ansible_ssh_pipelining: no
    env: "{{ vpc_env }}"
    # Options - lower case: staging | prod
    azone: "az1"
    # Options: az1 | az2 | az3
    sub_zone: "app"
    role_type: "{{ role_type| default('vmi') }}"
    # Options: vmi | smh | smh_app

    sg_zone: "{{ vpc_env }}-{{ role_type }}-APP"
    env_az: "{{ vpc_env }}-{{ azone }}"
    #    env_cf_data_version: "20"
    #    env_cf_app_version: "01"
    build_subnet_id: null
    replacement_time: "{{ ansible_date_time.iso8601_basic_short }}"
  vars_files:
    - "./../../vars/environment/{{ vpc_env }}/{{ role_type }}/vault.yml"
    - "./../../vars/environment/{{ vpc_env }}/{{ role_type }}/env.yml"
    - "./../../vault/environment/{{ vpc_env }}/vault.yml"
    - "./../../vars/environment/{{ vpc_env }}/env.yml"
    - "./../../vars/common.yml"

  roles:
    - "../../roles/deploy_ready"
    - "../../roles/deploy_make_ami"
