---
# playbook/server/server_app_scale.yml
# Created: 2020-02-23
# cdex-deploy
# Purpose: Create Auto Scaling Group
#
# https://medium.com/qbits/immutable-deployment-using-aws-application-load-balancing-ade3e70b00e8

- name: scale server
  hosts: localhost
  connection: local
  # hosts: "{{ variable_host| default('tag_function_BaseInstance:tag_workflow_JustCreated') }}"
  remote_user: "{{ remote_user_account }}"
  vars:
    ansible_ssh_pipelining: no
    env: "{{ vpc_env }}"
    # Options - lower case: staging | prod
    azone: "az1"
    # Options: az1 | az2 | az3
    sub_zone: "app"
    role_type: "{{ role_type| default('vmi') }}"
    # Options: vmi | smh | smh_app

    sg_zone: "{{ vpc_env }}-{{ role_type }}-APP"
    env_az: "{{ vpc_env }}-{{ azone }}"
    #    env_cf_data_version: "20"
    #    env_cf_app_version: "01"
    build_subnet_id: null
    replacement_time: "{{ ansible_date_time.iso8601_basic_short }}"
  vars_files:
    - "./../../vault/environment/{{ vpc_env }}/{{ role_type }}/vault.yml"
    - "./../../vars/environment/{{ vpc_env }}/{{ role_type }}/env.yml"
    - "./../../vault/environment/{{ vpc_env }}/vault.yml"
    - "./../../vars/environment/{{ vpc_env }}/env.yml"
    - "./../../vars/common.yml"

  roles:
    # - role: "../../roles/mgmt-controller/install_tools"
    - role: "../../roles/deploy/ready"
    - role: "../../roles/deploy/make_ami"
    - role: "../../roles/notify/slack/tasks/generic"
      notify_msg: "AMI Created for {{ vpc_env }}-{{ role_type }}: {{ ami_info.image_id }} for Launch Config:{{ vpc_env }}-{{ role_type }}-LT\n{{ launch_template_info }}"
      notify_slack_channel: "#afbh-updates"
      notify_slack_user: "afbh-mgmt-controller"

    - role: "../../roles/notify/team/tasks/generic"
      notify_msg: "AMI Created for {{ vpc_env }}-{{ role_type }}: {{ ami_info.image_id }} for Launch Config:{{ vpc_env }}-{{ role_type }}-LT\n{{ launch_template_info }}"
      notify_teams_webhook: "{{ teams_webhook }}"

