---
# roles/postgres_setup/tasks/main.yml
# Created: 2019-09-09
# cdex-deploy
# Purpose: Setup Postgres database
#
#    
#    

- name: pip install psycopg2 to virtualenv
  pip:
    name: psycopg2
    state: present
    virtualenv: "{{ base_app_directory }}/{{ role_type }}/{{ virtual_env_dir }}"

- name: pip install psycopg2 to base environment
  become_user: "{{ remote_admin_account }}"
  become: yes
  pip:
    name: psycopg2
    state: present

- name: "setup .pgpass file"
  template:
    src: "templates/pgpass"
    dest: "/home/{{ remote_user_account }}/.pgpass"
    mode: "0400"

- name: "create database in postgres for {{ role_type }}_{{ vpc_env }}"
  # raw: "createdb -h {{ rds_endpoint }} -p {{ env_rds_port }} -U {{ rds_username }} {{ role_type }}_{{ vpc_env }}"
  postgresql_db:
    login_host: "{{ rds_endpoint }}"
    login_user: "{{ rds_username }}"
    login_password: "{{ db_master_pw }}"
    port: "{{ env_rds_port }} "
    name: "{{ role_type }}_{{ vpc_env }}"

    state: present
- name: "Update postgres settings"
  raw: "psql -h {{ rds_endpoint }} -p {{ env_rds_port }} -U {{ rds_username }} -d {{ role_type }}_{{ vpc_env }} -c \"ALTER ROLE {{ rds_username }} SET client_encoding TO 'utf8'; ALTER ROLE {{rds_username }} SET default_transaction_isolation TO 'read committed';ALTER ROLE {{ rds_username }} SET timezone TO 'UTC';\""

- name: "grant all privileges"
  raw: "psql -h {{ rds_endpoint }} -p {{ env_rds_port }} -U {{ rds_username }} -d {{ role_type }}_{{ vpc_env }} -c \"GRANT ALL PRIVILEGES ON DATABASE {{ role_type }}_{{ vpc_env }} TO {{ rds_username }};\""
