---
# roles/notify_slack/tasks/main.yml
# Created: 2019-09-19
# cdex-deploy
# Purpose: Notify slack of successful configuration
#

- name: notify slack
  slack:
    token: "{{ slack_token_update_channel }}"
    msg: "{{ role_type }} updated in {{ vpc_env }} at {{ configure_time }} from https://github.com/TransparentHealth/{{ system_repository_name[role_type] }} Branch: {{ git_branch[role_type] }}"
    username: "afbh-mgmt-controller"
    channel: "#afbh-updates"
  delegate_to: localhost
