---

- name: "Creating Appserver User {{ app_pyapps_user }} - {{ app_superuser_username }}"
  become_user: "{{ remote_admin_account }}"
  become: yes
  user:
    name: "{{ app_pyapps_user }}"
    password: "{{ app_pyapps_pwd | password_hash('sha512') }}"

