---
# roles/check_web_is_up/tasks/main.yml
# Created: 2019-09-12
# cdex-deploy
# Purpose: check a website is up
#


- name: "check {{ role_type }} is up and operating correctly "
  uri:
    url: "http://{{ variable_host }}"
    status_code: ["200", "301"]
    return_content: yes
  register: web_check

- debug:
    msg:
      - "RETURNED: {{ web_check.status }}"
      - "REDIRECTED: {{ web_check.redirected }}"
      - "BODY:"
      - "{{ web_check.content }}"

