---
# roles/configure?_app/tasks/main.yml
# Created: 2019-09-15
# cdex-deploy
# Purpose:
#     Run migrate
#     createsuperuser
#    
#    

- name: run migrate
  django_manage:
    command: migrate
    app_path: "{{ base_app_directory }}/{{ role_type }}"
    virtualenv: "{{ base_app_directory }}/{{ role_type }}/{{ virtual_env_dir }}"

- name: "django create superuser - {{ app_pyapps_user }}"
  django_manage:
    virtualenv: "{{ base_app_directory }}/{{ role_type }}/{{ virtual_env_dir }}"
    app_path: "{{ base_app_directory }}/{{ role_type }}/{{ virtual_env_dir }}"
    command: "create_super_user_from_envars"

