---
# roles/configure?_app/tasks/main.yml
# Created: 2019-09-15
# cdex-deploy
# Purpose:
#     Run migrate
#     createsuperuser
#    
#    

- name: install npm for SASS/CSS Build
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name: npm
    state: present

- name: make node
  shell: "cd {{ base_app_directory }}/{{ role_type }}/assets && make"

- name: build assets
  shell: "cd {{ base_app_directory }}/{{ role_type }}/assets && make build"
  when: role_type == "smh_app"

- name: run migrate
  django_manage:
    command: migrate
    app_path: "{{ base_app_directory }}/{{ role_type }}"
    virtualenv: "{{ base_app_directory }}/{{ role_type }}/{{ virtual_env_dir }}"

- name: collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ base_app_directory }}/{{ role_type }}"
    virtualenv: "{{ base_app_directory }}/{{ role_type }}/{{ virtual_env_dir }}"
  register: static_result
  changed_when: '"0 static files" not in static_result.out'

- name: "django create superuser - {{ app_pyapps_user }}"
  django_manage:
    virtualenv: "{{ base_app_directory }}/{{ role_type }}/{{ virtual_env_dir }}"
    app_path: "{{ base_app_directory }}/{{ role_type }}"
    command: "create_super_user_from_envars"
  when: role_type != "smh"
