---
# roles/aws/cloudwatch_install/tasks/main.yml
# Created: 2019-10-11
# cdex-deploy
# Purpose:
# Setup cloudwatch to pull logs from EC2 instances
#    
# Based on documentation from:
#
# https://www.petefreitag.com/item/868.cfm
#

- name: Get cloudwatch agent package
  get_url:
    url: "https://s3.amazonaws.com/amazoncloudwatch-agent/debian/amd64/latest/amazon-cloudwatch-agent.deb"
    dest: "/home/{{ remote_user_account }}/amazon-cloudwatch-agent.deb"
    mode: "0644"

- name: Install cloudwatch agent
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: "sudo dpkg -i -E /home/{{ remote_user_account }}/amazon-cloudwatch-agent.deb "

- name: Add cwagent to adm group
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: "sudo usermod -aG adm cwagent "

- name: Create cwagent home directory
  become_user: "{{ remote_admin_account }}"
  become: yes
  file:
    path: "/home/cwagent"
    state: directory
    owner: cwagent
    mode: "0760"

- name: "create /home/cwagent/.aws"
  become_user: "{{ remote_admin_account }}"
  become: yes
  file:
    path: "/home/cwagent/.aws"
    state: directory
    mode: "0760"

- name: "install /home/cwagent/.aws/config"
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: templates/aws_config
    dest: "/home/cwagent/.aws/config"
    mode: "0400"

- name: "install /home/cwagent/.aws/credentials"
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: templates/aws_credentials
    dest: "/home/cwagent/.aws/credentials"
    mode: "0400"
    owner: cwagent


- name: Setup cwagent config file
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: templates/common-config.toml
    dest: "/opt/aws/amazon-cloudwatch-agent/etc/common-config.toml"
    owner: cwagent

- name: enable cloudwatch
  become_user: "{{ remote_admin_account }}"
  become: yes
  systemd:
    name: amazon-cloudwatch-agent.service
    state: started
    enabled: yes

