---
# roles/aws/cloudwatch_install/tasks/main.yml
# Created: 2019-10-11
# cdex-deploy
# Purpose:
# Setup cloudwatch to pull logs from EC2 instances
#    
# Based on documentation from:
#
# https://www.petefreitag.com/item/868.cfm
#

- name: Get cloudwatch agent package
  get_url:
    url: "https://s3.amazonaws.com/amazoncloudwatch-agent/debian/amd64/latest/amazon-cloudwatch-agent.deb"
    dest: "/home/{{ remote_user_account }}/amazon-cloudwatch-agent.deb"
    mode: "0644"

- name: Install cloudwatch agent
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: "sudo dpkg -i -E /home/{{ remote_user_account }}/amazon-cloudwatch-agent.deb "

- name: Add cwagent to adm group
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: "sudo usermod -aG adm cwagent "

