---
# roles/app/base/tasks/main.yml
# Created: 2019-09-09
# cdex-deploy
# Purpose: Install components for Postgres, Nginx and Gunicorn on Ubuntu 18.04
#
#    
#    

- name: "upgrade and update packages"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400  # One Day
  # raw: "sudo apt-get -y upgrade"

- name: "add packages for python3"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name:
      - python3-dev
      - python3-pip
      - libpq-dev
      - postgresql
      - postgresql-contrib
      - postgresql-client-common
      - nginx
      - curl
    state: present

