---
# roles/app/base/tasks/main.yml
# Created: 2019-09-09
# cdex-deploy
# Purpose: Install components for Postgres, Nginx and Gunicorn on Ubuntu 18.04
#
#    
#    

- name: "update packages"
  raw: "sudo apt-get -y update"

- name: "add packages for python3"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name: ["python3-dev", "python3-pip", "libpq-dev", "postgresql", "postgresql-contrib", "postgresql-client-common", "nginx", "curl"]
    state: present

- name: "update packages"
  raw: "sudo apt-get -y update"

- name: "upgrade packages"
  raw: "sudo apt-get -y upgrade"

