---
# notify_teams/tasks/main.yml
# Created: 2019-09-21
# cdex-deploy
# Purpose: Send notification to Teams BB2,0/alliance channel
#
#    

- name: Send CDA2FHIR Update for SMH Service
  office_365_connector_card:
    webbhook: "{{ teams_webhook }}"
    text: "{{ vpc_env|upper }}: {{ configure_time }} - CDA2FHIR Service ({{ cda2fhir_private_ip }}:{{ cda2fhir_service_port }}) reported: {{ web_check.content }}"
  delegate_to: localhost
  when: role_type == "smh"

- name: Send Teams notification
  office_365_connector_card:
    webhook: "{{ teams_webhook }}"
    text: "{{ role_type }} updated in {{ vpc_env }} at {{ configure_time }} from https://github.com/TransparentHealth/{{ system_repository_name[role_type] }} Branch: {{ git_branch[role_type] }}"
  delegate_to: localhost
