---
- name: "install nginx"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name: "nginx"
    state: present
    # update_cache: yes
    force_apt_get: yes

# Get vmi/.nginx/{{ role_type }}/nginx.conf out of repo
# pull to tmp and use as template source to push to /etc/nginx/nginx.conf


- name: "remove default config files"
  become_user: "{{ remote_admin_account }}"
  become:
  file:
    path: "/etc/nginx/conf.d/default.conf"
    state: absent

- name: "create group logreader"
  become_user: "{{ remote_admin_account }}"
  become: yes
  group:
    name: logreader
    system: yes
    state: present

- name: "set permission on nginx log dir"
  become: yes
  become_user: "{{ remote_admin_account }}"
  file:
    path: /var/log/nginx
    state: directory
    mode: 0755
    group: "logreader"

- name: "install uwsgi"
  become: yes
  become_user: "{{ remote_admin_account }}"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - uwsgi

- name: "copy nginx.conf to the target"
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src:  templates/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: "Copy Gunicorn to virtualenv bin"
  template:
    src: templates/gunicorn_start
    dest: "{{ base_app_directory }}/{{ role_type }}/env/bin/gunicorn_start"
    mode: 0644
    owner: "{{ remote_user_account }}"
    group: "{{ remote_user_account }}"

- name: "Copy default vhost file in to /etc/nginx/site-available"
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: templates/nginx_default
    dest: "/etc/nginx/sites-enabled/default"
    owner: "{{ remote_admin_account }}"
    group: "www-data"
    mode: "0644"

- name: "create sock path"
  become_user: "{{ remote_admin_account }}"
  become: yes
  file:
    path: "/var/pyapps/{{ role_type }}"
    state: directory
    mode: "0664"

- name: "create sock file"
  become_user: "{{ remote_admin_account }}"
  become: yes
  file:
    path: "/var/pyapps/{{ role_type }}/pyapps.sock"
    state: touch
    mode: "0664"


- name: "enable nginx"
  become_user: "{{ remote_admin_account }}"
  become: yes
  service:
    name: nginx
    enabled: yes

- name: "enable uwsgi"
  become_user: "{{ remote_admin_account }}"
  become: yes
  service:
    name: uwsgi
    enabled: yes

- name: "install supervisor"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name: supervisor
    state: present

- name: configure gunicorn as service
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: templates/gunicorn_service
    dest: "/etc/systemd/system/gunicorn.service"
    mode: "0644"
    owner: "{{ remote_admin_account }}"
    group: "{{ remote_admin_account }}"

- name: "configure supervisord/conf.d/ {{ system_repository_name[role_type] }}.conf"
  become_user: "{{ remote_admin_account }}"
  become: yes
  template:
    src: templates/supervisor_conf
    dest: "/etc/supervisord/conf.d/{{ system_repository_name[role_type] }}.conf"
    mode: "0644"
    owner: "{{ remote_admin_account }}"
    group: "{{ remote_admin_account }}"
