# tasks/app/nginx_install.yml
# install nginx with latest version
# pre-installed software:
#   - python 3.6.8
#   - git

---
- hosts: "base_instance-{{ role_type }}"
  gather_facts: True
  become: yes
  root_user: ubuntu
  tasks:
    - name: "Installing latest nginx version"
      apt:
        name: "nginx"
        update_cache: yes
        state: present

    - name: start nginx
      service:
        name: nginx
        state: started

