# tasks/app/nginx_install.yml
# install nginx with latest version
# pre-installed software:
#   - python 3.6.8
#   - git

---
- hosts: "{{ new_instance.add_host.host_name }}"
  tasks:
    - debug:
        msg: "{{ new_instance.add_host.host_name }}"

    - name: "Installing latest nginx version"
      apt:
        name: "nginx"
        update_cache: yes
        state: present

    - name: start nginx
      service:
        name: nginx
        state: started

