---
# roles/deploy_ready/tasks/main.yml
# Created: 2019-09-11
# cdex-deploy
# Purpose: update tags on server to identify deployment readiness
#
#    
#

- name: get ec2 facts
  ec2_instance_facts:
  register: ec2_facts_info

- name: "Get resource_id of ec2_instance"
  debug:
    msg: "{{ ec2_facts_info }}"

- name: get ec2 facts
  ec2_instance_facts:
    filters:
      "tag:workflow": "JustCreated"
  register: ec2_facts_info_id

- name: "Get resource_id of ec2_instance"
  debug:
    msg: "{{ ec2_facts_info_id }}"

- name: "update ec2 tags on built ec2 instance"
  ec2_tag:
    region: "{{ aws_region }}"
    resource:
