---
# roles/git_deploy/tasks/main.yml
# Created: 2019-09-05
# cdex-deploy : 
# Purpose:
# deploy git.{{ role_type }} to target

 NOTE: .gitmodules should use https references to sub modules
#

- name: "remove target directory: /home/{{ remote_user_account }}/cdex.{{ vpc_env }}"
  become_user: "{{ remote_admin_account }}"
  become: yes
  file:
    path: "/home/{{ remote_user_account }}/cdex.{{ vpc_env }}"
    state: absent

- name: "git clone cdex.{{ vpc_env }}"
  git:
    repo: "https://github.com/transparenthealth/cdex.{{ vpc_env }}.git"
    dest: "/home/{{ remote_user_account }}/cdex.{{ vpc_env }}"
    clone: yes
    force: yes
    version: "{{ git_branch | default('HEAD') }}"


