---
# roles/git_deploy/tasks/main.yml
# Created: 2019-09-05
# cdex-deploy : 
# Purpose:
# deploy git.{{ role_type }} to target
#    
#    

- name: "git clone cdex.{{ vpc_env }}"
  git:
    repo: "https://github.com/transparenthealth/cdex.{{ vpc_env }}.git"
    dest: "/home/{{ remote_user_account }}/{{cdex.{{ vpc_env }}"
    clone: yes
    force: yes
    version: "{{ git_branch | default('HEAD') }}"

- name: "git clone {{ role_type }} into cdex.{{ vpc_env }}"
  git:
    repo: "https://github.com/transparenthealth/{{ role?-type }}.git"
    dest: "/home/{{ remote_user_account }}/{{cdex.{{ vpc_env }}/{{ role_type }}"
    clone: yes
    force: yes


