---
# File: roles/python34/tasks/main.yml
# Created: 5/10/17
# Author: '@ekivemark'
# download and install python3
# Check for python version

- name: "Install Python 3.6 and supporting copmponents"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-dev
    # - python3-venv

