---
# File: roles/python34/tasks/main.yml
# Created: 5/10/17
# Author: '@ekivemark'
# download and install python3
# Check for python version

- name: "Install Python 3.6 and supporting components"
  become_user: "{{ remote_admin_account }}"
  become: yes
  shell: |
    cd ~
    wget https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tgz
    sudo cd /opt
    sudo tar -xvf ~/Python-3.6.3.tgz
    cd Python-3.6.3/
    sudo ./configure
    sudo make
    sudo make install
    rm -Rf ~/.cache
    python 3.6 -V
  register: result_python_install

- debug:
    msg: "Result: \n {{ result_python_install }}"

- name: "install virtualenv"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name: ["python-virtualenv"]
    state: present

