---
# File: roles/python34/tasks/main.yml
# Created: 5/10/17
# Author: '@ekivemark'
# download and install python3
# Check for python version

- name: "Install Python 3.6 and supporting components"
  become_user: "{{ remote_admin_account }}"
  become: yes
  apt:
    name: ["python3-dev", "python-virtualenv"]
    state: present

